In [0]:
# NumPy를 사용하여 실행합니다
import numpy as np
storages = np.array([1, 2, 3, 4])
storages += storages
print(storages)


[2 4 6 8]


In [0]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [0]:
arr = np.arange(10)
arr[0:3] = 1
print(arr)


[1 1 1 3 4 5 6 7 8 9]


In [0]:
import numpy as np

# ndarray를 그대로 arr2 변수에 대입한 경우를 살펴봅시다
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# arr2 변수를 변경하면 원래 변수(arr1)도 영향을 받고 있습니다
print(arr1)

# ndarray를 copy()를 사용해 arr2 변수에 대입한 경우를 살펴봅시다
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# arr2 변수를 변경해도 원래 변수(arr1)에 영향을 주지 않습니다
print(arr1)


[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


In [0]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 변수 arr의 각 요소를 절대값으로 하여 변수 arr_abs에 대입하세요
arr_abs = np.abs(arr)
print(arr_abs)

# 변수 arr_abs의 각 요소의 e의 거듭제곱과 제곱근을 출력하세요
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))


[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [0]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# np.unique() 함수를 사용하여 중복을 제거한 배열을 변수 new_arr1에 대입하세요
new_arr1 = np.unique(arr1)
print(new_arr1)

# 변수 new_arr1과 변수 arr2의 합집합을 출력하세요
print(np.union1d(new_arr1, arr2))

# 변수 new_arr1과 변수 arr2의 교집합을 출력하세요
print(np.intersect1d(new_arr1, arr2))

# 변수 new_arr1에서 변수 arr2을 뺀 차집합을 출력하세요
print(np.setdiff1d(new_arr1, arr2))


[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [0]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1])

[4 5 6]


In [0]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,2])

6


In [0]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,1:])

[5 6]


In [0]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr) 

# 변수 arr의 요소 중 3을 출력하세요
print(arr[0, 2])

# 변수 arr에서 부분적으로 꺼내어 출력하세요
# "1행 이후, 1열까지"를 꺼냅니다
print(arr[1:, :2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


In [0]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])

print(arr.sum())
print(arr.sum(axis=0)) # 열의 합
print(arr.sum(axis=1)) # 행의 합


21
[5 7 9]
[ 6 15]


In [0]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# arr 행의 합을 구하여 문제에서 제시한 1차원 배열을 반환하세요
print()


[ 6 21 57]


In [0]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# 3행, 2행, 0행을 순서대로 추출하여 새로운 요소를 만듭니다
# 인덱스 번호는 0부터 시작합니다
print(arr[[3, 2, 0]])


[[7 8]
 [5 6]
 [1 2]]


In [0]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 변수 arr을 전치하세요
print(arr.T) # print(np.transpose(arr))

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [0]:
arr = np.array([15, 30, 5])
arr.argsort() # 작은값부터 순서대로 데이터의 위치를 반환

array([2, 0, 1])

In [0]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# argsort() 메서드로 출력하세요
print(arr.argsort())

# np.sort() 함수로 정렬하여 출력하세요
print(np.sort(arr))

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]


In [0]:
import numpy as np

# arr을 정의합니다
arr = np.arange(9).reshape(3, 3)
print(arr)
# 변수 arr와 arr의 행렬곱을 출력하세요
print(np.dot(arr, arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [0]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 변수 arr의 각 열의 평균을 출력하세요
print(arr.mean(axis=0))

# 변수 arr의 행 합계를 출력하세요
print(arr.sum(axis=1))

# 변수 arr의 최소값을 출력하세요
print(arr.min())

# 변수 arr의 각 열의 최대값의 인덱스 번호를 출력하세요
print(arr.argmax(axis=0))


[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


In [0]:
x = np.arange(6).reshape(2, 3)
print(x + 1)

[[1 2 3]
 [4 5 6]]


In [0]:
import numpy as np

np.random.seed(100)

# 각 요소가 0 ~ 30인 정수 행렬(5 × 3)을 변수 arr에 대입하세요
arr = np.random.randint(0, 31, (5, 3))
print(arr)

# 변수 arr을 전치하세요
arr = arr.T
print(arr)

# 각 열의 평균을 출력하세요
print(arr.mean(axis = 0))

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]
[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]
[11.66666667 15.         18.66666667 14.33333333  6.        ]
